version: '1.2'

services:
  mysql:
    image: mysql:8.4.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  
  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
  # add 1.1
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    environment:
      JENKINS_OPTS: "--httpPort=8080"
  #add 1.2
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    restart: always
    tty: true  # To keep the container running
    stdin_open: true # To interact with the container
    volumes:
      - ./ubuntu:/root
    command: >
      /bin/bash -c 
      "apt-get update && 
      apt-get install -y curl && 
      apt-get install -y sudo && 
      echo 'root:root' | chpasswd &&
      tail -f /dev/null"